### ISSUE TITLE
COSTOS DE MITIGACIÓN AMBIENTAL

### ISSUE THREAD

**Issue by GEERMUTH** [ORFEI-GRAP/Proyecto-034-ESPIRULINA#12]
Ing. NELA, necesito el resumen de los costos de mitigación ambiental del proyecto, URGENTE.

Ing. Nela le reclaco que requiero los costos de mitigación ambiental del proyecto, para hoy, URGENTE.

**Comment by nelamendozaflores** [comment]
ING. GERMUTH YA subí  EL PRESUPUESTO AMBIENTAL el lunes 15 de junio en cumplimento a la tarea asignada, 
[presupuesto amb.xlsx](https://github.com/ORFEI-GRAP/Proyecto-034-ESPIRULINA/files/4799710/presupuesto.amb.xlsx)

**Comment by nelamendozaflores** [comment]
el presupuesto del proyecto ambiental
[presupuesto amb.xlsx](https://github.com/ORFEI-GRAP/Proyecto-034-ESPIRULINA/files/4873346/presupuesto.amb.xlsx)
