### ISSUE TITLE
ESTUDIOS DE IMPACTO AMBIENTAL

### ISSUE THREAD

**Issue by GEERMUTH** [ORFEI-GRAP/Proyecto-034-ESPIRULINA#13]
SUBSANACIÓN DE OBSERVACIONES
Ing. Nela Sírvase subsanar las observaciones de los estudios y/o análisis de impacto ambiental de los siguientes Proyectos de Inversión:
- [x] Proyecto de Inversión “MEJORAMIENTO Y CREACIÓN DE SERVICIOS TURÍSTICOS PÚBLICOS EN EL CAÑÓN DEL APURIMAC, DISTRITOS DE CURAHUASI, SAN PEDRO DE CACHORA, HUANIPACA, TAMBURCO Y ABANCAY - REGIÓN APURIMAC”.

- [x] Proyecto de Inversión "MEJORAMIENTO DE LOS SERVICIOS DE LA DIRECCION REGIONAL DE LA PRODUCCION - DIRECCION DE INDUSTRIA, DE LA PROVINCIA DE ABANCAY DEL DEPARTAMENTO DE APURÍMAC" .

- [x] “MEJORAMIENTO DE LOS SERVICIOS TURÍSTICOS EN EL CONJUNTO ARQUEOLÓGICO DE SAYWITE, DISTRITO DE CURAHUASI, PROVINCIA DE ABANCAY, REGIÓN APURÍMAC”. 

Para todos los estudios las sugerencias de subanación de observaciones son las mismas y se detallan a continuación:
- Los estudios deben redactarse con las Normas APA (American Phychological Association); que son estandares de presentación de trabajos escritos a nivel internacional.
-  La presentación de los estudios debe ser correcta, no deben redundarse los párrafos, los cuadros y páginas deben configurarse, es decir que la presentación de los estudios debe ser la adecuada.
-  La numeración de los cuadros debe seguir una secuencia enumerada.
- El análisis ambiental que se realiza para cada debe ser diferente de uno del otro ya que cada uno de los proyectos de inversión son distintos.
- La identificación del los impactos debe ser de acuerdo a la tipología del Proyecto de Inversión.
-  Debe interpretar los cuadros y en especial la matriz de Leopold, en las etapas de habilitación, Construcción, funcionamiento...
-  Debe ser más entendible la descripción de los impactos ambientales en las etapas de habilitación, Construcción, funcionamiento...
-  Debe mejorar las conclusiones y recomendaciones; es decir lo que se analiza se concluye, y recomienda lo que se concluye.
-  Cada estudio debe tener sus conclusiones y recomendaciones.
-  El presupuesto de Mitigación Ambiental no va al final de los estudios ¿a antes¡, se sugiere corregir.
-  En los estudios debe mencionar que componentes se intervendran.

- [x] En términos generales debe subsanar cada estudio y estará sujeto a una nueva revisión.

- [x] El plazo para la subsanación es de 02 días hábiles.

ATT.

Ing. GERMUTH ALVITES ASCUE

**Comment by nelamendozaflores** [comment]
buendía ing Germuth, envío el análisis Ambiental,con observaciones levantados según  sus recomendaciones

**Comment by nelamendozaflores** [comment]
[IMPACTO AMBIENTAL-PI ESPIRULINA-COMPATIBLE.docx](https://github.com/ORFEI-GRAP/Proyecto-034-ESPIRULINA/files/4857861/IMPACTO.AMBIENTAL-PI.ESPIRULINA-COMPATIBLE.docx)

**Comment by nelamendozaflores** [comment]
[IMPACTO AMBIENTAL-CAÑON APURIMAC.docx](https://github.com/ORFEI-GRAP/Proyecto-034-ESPIRULINA/files/4857880/IMPACTO.AMBIENTAL-CANON.APURIMAC.docx)

**Comment by nelamendozaflores** [comment]
[ANÁLISIS AMBIENTAL-CAÑON APURIMAC.docx](https://github.com/ORFEI-GRAP/Proyecto-034-ESPIRULINA/files/4857948/ANALISIS.AMBIENTAL-CANON.APURIMAC.docx)

**Comment by nelamendozaflores** [comment]
[ANÁLISIS DEL IMPACTO AMBIENTAL-CAÑON APURIMAC.docx](https://github.com/ORFEI-GRAP/Proyecto-034-ESPIRULINA/files/4858325/ANALISIS.DEL.IMPACTO.AMBIENTAL-CANON.APURIMAC.docx)

**Comment by nelamendozaflores** [comment]
[ANALISIS.DEL.IMPACTO.AMBIENTAL-CANON.APURIMAC.docx](https://github.com/ORFEI-GRAP/Proyecto-034-ESPIRULINA/files/4869962/ANALISIS.DEL.IMPACTO.AMBIENTAL-CANON.APURIMAC.docx)
